### ISSUE TITLE
Make README of sub dirs self contained

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/xenon-docker-images#10]
On Docker Hub the description should be self-explanatory.

**Comment by sverhoeven** [comment]
For example add a configuration chapter like https://github.com/NLeSC/xenon-docker-images/blob/master/xenon-torque/README.md#configuration

**Comment by jspaaks** [comment]
done, e.g. 
- https://hub.docker.com/r/nlesc/xenon-slurm/
- example of an intermediate image https://hub.docker.com/r/nlesc/xenon-slurm-abstract/
