### ISSUE TITLE
Slurm container fails to start

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/xenon-docker-images#22]
The mysqld is not starting correctly.
In the mysql log it says something like:
```
 Fatal error: Can't open and lock privilege tables
```

The start script tries to make a mysql connection indefinitely causing the whole container to pause midway the boot process.

**Comment by sverhoeven** [comment]
Unable to reproduce localy or on Travis-CI.

Started working in `mysql-init` branch to initialize/startup mysql by not using `service mysql start` to see if it fixes it.

**Comment by jmaassen** [comment]
I've created a version which does not use mysql at all but logs to a file. Seems to work fine, Xenon passes the integration tests on slurm 15. Added bonus is smaller container and slightly faster startup.

I'll clean it up, add slurm 14, 16 and 17 and send a pull request.

**Comment by sverhoeven** [comment]
Merged `jason` branch, added boatswain config to build images locally in right order.

Updated Docker Hub by reconfiguring links and dropping xenon-slurm-munge, xenon-slurm-mysql and xenon-slurm-supervisor images.

**Comment by sverhoeven** [comment]
Triggering build in right order on Docker Hub now, afterwards will trigger Travis-CI builds.
